version: '2'

services:
  orderer:
    container_name: orderer
    image: hub.51chain.net/hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=orderer
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=genesis.block
      - ORDERER_GENERAL_LOCALMSPID=DEFAULT
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp
      - GRPC_TRACE=all=true,
      - GRPC_VERBOSITY=debug
      - ORDERER_General_TLS_Enabled=false
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./msp:/etc/hyperledger/msp
      - ./genesis.block:/etc/hyperledger/fabric/genesis.block
    ports:
      - 7050:7050
  peer:
    container_name: peer
    image: hub.51chain.net/hyperledger/fabric-peer
    environment:
      - CORE_PEER_ID=peer
      - CORE_PEER_ADDRESS=peer:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer:7051
      - CORE_PEER_LOCALMSPID=DEFAULT
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_PEER_TLS_ENABLED=false
    volumes:
        - /var/run/:/host/var/run/
        - ./msp:/etc/hyperledger/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start --peer-chaincodedev=true -o orderer:7050
    ports:
      - 7051:7051
      - 7053:7053
    depends_on:
      - orderer
      - couchdb0

  cli:
    container_name: cli
    image: hub.51chain.net/hyperledger/fabric-tools:x86_64-1.0.0-rc1-snapshot-a709058
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer:7051
      - CORE_PEER_LOCALMSPID=DEFAULT
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
      - CORE_PEER_TLS_ENABLED=false

    working_dir: /opt/gopath/src/chaincodedev
    command: /bin/bash -c './script.sh'
    volumes:
        - /var/run/:/host/var/run/
        - ./msp:/etc/hyperledger/msp
        #- ./chaincode:/opt/gopath/src/chaincodedev/chaincode
        - ./:/opt/gopath/src/chaincodedev/
        #- ./../../projects:/opt/gopath/src/chaincodedev/chaincode
    depends_on:
      - orderer
      - peer

  couchdb0:
    container_name: couchdb0
    image: hub.51chain.net/hyperledger/fabric-couchdb:x86_64-1.0.0
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "5984:5984"
###
  #chaincode:
    #container_name: chaincode
    #image: hub.51chain.net/hyperledger/fabric-ccenv:x86_64-1.0.0-rc1-snapshot-a709058
    #tty: true
    #environment:
      #- GOPATH=/opt/gopath
      #- CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      #- CORE_PEER_ID=example02
      #- CORE_PEER_ADDRESS=peer:7051
      #- CORE_PEER_LOCALMSPID=DEFAULT
      #- CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp
    #working_dir: /opt/gopath/src/chaincode
    #command: /bin/bash -c 'sleep 6000000'
    #volumes:
        #- /var/run/:/host/var/run/
        #- ./msp:/etc/hyperledger/msp
        #- ./../chaincode:/opt/gopath/src/chaincode
   #depends_on:
      #- orderer
      #- peer
###
